### ISSUE TITLE
你好请问x264以及ssl怎么编入ffmpeg？

### ISSUE THREAD

**Issue by StephenGiant** [zuguorui/FFmpegAudioPlayer#1]
大佬的播放器格式支持没问题

**Comment by zuguorui** [comment]
SSL我没有编过，好像FFmpeg本身就支持的。x264是额外的库，需要你单独编译后，在编译FFmpeg时打开x264选项并且链接到x264库。这个我写了一篇博客，你可以参考。https://blog.csdn.net/zuguorui/article/details/104150008。使用FFmpeg解码视频并播放你可以参考我的另一个工程FFmpeg-VideoPlayer，但是效果不好，因为使用的是软解，很卡。
